# Generated by cpp11: do not edit by hand

fun <- function() {
  invisible(.Call(`_statart_fun`))
}

df_to_mat <- function(tb, na) {
  .Call(`_statart_df_to_mat`, tb, na)
}

row_max_dbl <- function(tb) {
  .Call(`_statart_row_max_dbl`, tb)
}

row_min_dbl <- function(tb) {
  .Call(`_statart_row_min_dbl`, tb)
}

row_sum_dbl <- function(tb) {
  .Call(`_statart_row_sum_dbl`, tb)
}

row_mean_dbl <- function(tb) {
  .Call(`_statart_row_mean_dbl`, tb)
}

row_unique_dbl <- function(tb) {
  .Call(`_statart_row_unique_dbl`, tb)
}
