# Generated by cpp11: do not edit by hand

row_sum <- function(tb) {
  .Call(`_statart_row_sum`, tb)
}

row_max <- function(tb) {
  .Call(`_statart_row_max`, tb)
}

row_min <- function(tb) {
  .Call(`_statart_row_min`, tb)
}

row_unique <- function(tb) {
  .Call(`_statart_row_unique`, tb)
}

s_sum <- function(vec) {
  .Call(`_statart_s_sum`, vec)
}

s_mean <- function(vec) {
  .Call(`_statart_s_mean`, vec)
}

s_max <- function(vec) {
  .Call(`_statart_s_max`, vec)
}

dbl_sd <- function(dbl_vec) {
  .Call(`_statart_dbl_sd`, dbl_vec)
}

n_distinct10k <- function(vec) {
  .Call(`_statart_n_distinct10k`, vec)
}

s_median <- function(vec) {
  .Call(`_statart_s_median`, vec)
}
